{{- if $.Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.secrets.name }}
  namespace: {{ $.Values.scoopNamespace | default .Release.Namespace }}
type: Opaque
{{- if $.Values.secrets.data }}
data:
{{ toYaml $.Values.secrets.data | b64enc | indent 2 }}
{{- end }}
{{- end }}

---

{{- if and  $.Values.scoop.imagePullSecrets.enabled  }}
{{- if not $.Values.scoop.imagePullSecrets.existingImagePullSecret }}
apiVersion: v1
kind: Secret
metadata: 
  name: scoop-imagepull-secret
  namespace: {{ $.Values.scoopNamespace | default .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
{{- if $.Values.scoop.imagePullSecrets.data}}
data:
{{- if $.Values.scoop.imagePullSecrets.data.value }}
  .dockerconfigjson: {{ $.Values.scoop.imagePullSecrets.data.value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}


