{{- if $.Values.readinessAndLivenessPolicy }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ .Chart.Name }}-restrict-without-readiness-liveness
spec:
  failurePolicy: Fail
  {{- if and .Values.readinessAndLivenessPolicyConfig.namespaces }}
  matchConstraints:
    matchPolicy: Equivalent
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          {{- range $.Values.readinessAndLivenessPolicyConfig.namespaces }}
          - {{ . | quote }}
          {{- end }}
  {{- else }}
  matchConstraints: {}
  {{- end }}
  objectSelector: {}
  resourceRules:
    - apiGroups:
        {{- range $.Values.readinessAndLivenessPolicyConfig.apiGroups }}
        - {{ . | quote }}
        {{- end }}
      apiVersions: ["v1"]
      operations:
        {{- range $.Values.readinessAndLivenessPolicyConfig.operations }}
        - {{ . | quote }}
        {{- end }}
      resources:
        {{- range $.Values.readinessAndLivenessPolicyConfig.resources }}
        - {{ . | quote }}
        {{- end }}
      scope: Namespaced
  validations:
  {{- if and .Values.bypassLabel.key .Values.bypassLabel.value }}
    - expression: >
        (has(object.metadata.labels) &&
         object.metadata.labels['{{ .Values.bypassLabel.key }}'] == '{{ .Values.bypassLabel.value }}') ||
        object.spec.template.spec.containers.all(container,
          has(container.readinessProbe) &&
          has(container.livenessProbe)
        )
      message: "Deployments without readiness and liveness probes are only allowed for '{{ .Values.bypassLabel.key }}: {{ .Values.bypassLabel.value }}'."
  {{- else }}
    - expression: object.spec.template.spec.containers.all(container,
        has(container.readinessProbe) && has(container.livenessProbe))
      message: "Deployments without readiness and liveness probes are not allowed"
  {{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ .Chart.Name }}-restrict-without-readiness-liveness
spec:
  policyName: {{ .Chart.Name }}-restrict-without-readiness-liveness
  validationActions:
  {{- range $.Values.readinessAndLivenessPolicyConfig.validationActions }}
  - {{ . }}
  {{- end }}
{{- end }}