global:
  # Twice a day
  schedule: "0 */12 * * *"
  # devtron-backups
  S3:
    # give the endpoint in case of non AWS storages with s3 protocol 
    enabled: true
    S3_BUCKET_NAME: "tfhgjkl;"
    S3_ACCESS_KEY: "adin"
    S3_SECRET_KEY: "admin123"
    AWS_REGION: "US"
    S3_ENDPOINT: "endpoint.com"
    CA_BUNDLE: "-----BEGIN CERTIFICATE-----\nMIIDcDCCAlgCCQDZJ13mz4IWGzANBgkqhkiG9w0BAQsFADB6MQswCQYDVQQGEwJJTjEQMA4GA1UECAwHSGFyeWFuYTEQMA4GA1UEBwwHR3VyZ2FvbjETMBEGA1UECgwKRGV2dHJvbkluYzEPMA0GA1UECwwGRGV2b3BzMSEwHwYDVQQDDBhzdGFnZS1taW5pby5kZXZ0cm9uLmluZm8wHhcNMjQxMTI4MDczNTEwWhcNMzQxMTI2MDczNTEwWjB6MQswCQYDVQQGEwJJTjEQMA4GA1UECAwHSGFyeWFuYTEQMA4GA1UEBwwHR3VyZ2FvbjETMBEGA1UECgwKRGV2dHJvbkluYzEPMA0GA1UECwwGRGV2b3BzMSEwHwYDVQQDDBhzdGFnZS1taW5pby5kZXZ0cm9uLmluZm8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJo7+FlCLdHEOY301eEaeuRmHB05alxMGPwqtIHUmf+fGK3SkuNEaYH1HKgywbzhpEV7mt9og/kxWhY6xVZP18Ys1H/AVLeNNrFeQinraniYM7/GWZXQl0ntcF7jjvdG2NoKJIlgw59BCq9flQmh+6qkIk35QxRI5dneQkrLIrltUl5gEHhZ+O3vnknh6d4KpoG7nyAnJL6MrcZ8hUNA0c9tcLPdtUk7NHNPfKgIsBa/F6Vk0ZB83l4JwTmxSkn0Z9KVx2bcyP2vMjfjm3It9PE4KDSmLCBeXjfsmYP1GFldz+DMb+UO2zZGywkOR+aUjkJgDN01+dNpV/k3zYbhFRAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAGr6nSMy+q3MKrR2jYO+2626ABf0hWFjFNLgwCy2G7Hq75Q8VzbJgswrtAyJvmYaaliWFdE/OGN4whiftZ2Kq/CaVK74d80JjqGVjocPzb9afBWmtoy66j9ZLnwGmlUVKaUE7hS7kze0daWzZeeskyPgqwuJZGpHoSkl5eQBQUIKsIhh5NokHZZi9WYraAHtOAHOkGm3PsVwpZGMY43nuTva6uEecr6UawGuZAwUkUPqOIj9NFixwdJ2bDwcPJ7Y9eZxgauTYUTYGGv/sCXMArzwWr2r72ve47NfG0EjwdmVJEkSJJLf4mXROPGWOjYBaY4ae9GFn/3Pf5wpE+mz30g=\n-----END CERTIFICATE-----"
    # set true if node has access of buckets
    # By default, the node has access to buckets. Set to false if the node should not have access.
    NODE_ROLE: ""
    # passphrase used to encrypt/decrypt the file (encryption is done by gpg)
    encryption:
      enabled: false
      passphrase: ""
    # image: quay.io/devtron/k8s-utils:ubuntu-aws-cli #default amd  
    # image: quay.io/devtron/k8s-utils:0b9f5ba5-395-11405 #arm
  AZURE:
    enabled: false
    AZURE_BLOB_ACCOUNT_NAME: ""
    AZURE_ACCOUNT_KEY: ""
    AZURE_BLOB_CONTAINER_FOR_POSTGRES: ""
    AZURE_BLOB_CONTAINER_FOR_ARGOCD: ""
    encryption:
      enabled: false # Recommended
      passphrase:  # Required if encryption is enabled

    # image: quay.io/devtron/k8s-utils:az-cli-ubuntu #amd
  GCP:
    enabled: false
    GCS_BUCKET_NAME: "" # Required if GCP is enabled
    CREDENTIALS: # Optional. Use only if in case node doesn't have permission to push over GCS.
      enabled: false
      # Only base64 Encoded JSON CREDENTIALS allowed. Example shown below.
      # GCP_CREDENTIALS_JSON: "eyJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsInByb2plY3RfaWQiOiAiPHlvdXItcHJvamVjdC1pZD4iLCJwcml2YXRlX2tleV9pZCI6ICI8eW91ci1wcml2YXRlLWtleS1pZD4iLCJwcml2YXRlX2tleSI6ICI8eW91ci1wcml2YXRlLWtleT4iLCJjbGllbnRfZW1haWwiOiAiPHlvdXItY2xpZW50LWVtYWlsPiIsImNsaWVudF9pZCI6ICI8eW91ci1jbGllbnQtaWQ+IiwiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLCJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLCJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiPHlvdXItY2xpZW50LWNlcnQtdXJsPiJ9Cg=="  
      GCP_CREDENTIALS_JSON: ""

    encryption:
      enabled: false # Recommended
      passphrase: "" # Required if encryption is enabled
    # image: google/cloud-sdk:alpine # default amd

  PERSISTENCE:
    enabled: false
    existingClaim: ""
    # size: 30Gi   # Required if existingClaim is not used
    storageClass: "" # Required if existingClaim is not used
    encryption:
      enabled: false # Recommended
      passphrase: "" # Required if encryption is enabled

argocdversion: v2

postgres_backup:
  # Reference to secret which as postgresql password in PG_PASSWORD key
  secretName: "devtron-secret"
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi
  # postgresImage: postgres:14
  # host: "postgresql-custom.devtroncd"

argocd_backup:
  serviceAccountName: "argocd-backup"
  enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi
  # argocdImage: quay.io/argoproj/argocd:v2.4.0
  # args: "argocd admin export -n devtroncd > /argocd/backup.yaml"

  # argocdImage: argoproj/argocd:v1.8.1  #(image for argo-V1)
  # args: argocd-util export --namespace devtroncd > /argocd/backup.yaml; #(argo-V1)
